/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class FormResultados extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormResultados
     */
    private String Partidos = "C:\\Users\\pc\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_Partidos\\src\\Archivos\\Partidos.txt";

    public FormResultados() {
        initComponents();
        this.setSize(910,600);
        this.setTitle("Resultados");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CARGAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CARGAR.setText("CARGAR");
        CARGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARGARMouseClicked(evt);
            }
        });
        getContentPane().add(CARGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        Resultados.setEditable(false);
        Resultados.setColumns(20);
        Resultados.setRows(5);
        jScrollPane1.setViewportView(Resultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CARGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGARMouseClicked
         // TODO add your handling code here:
        try (BufferedReader br = new BufferedReader(new FileReader(Partidos))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] Datos = linea.split("\\|");
                Resultados.append(Datos[5] + " - " + Datos[1] + " " + Datos[2] + " VS " + Datos[4] + " " + Datos[3]+"\n");
            }
            br.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
         
    }//GEN-LAST:event_CARGARMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CARGAR;
    private javax.swing.JTextArea Resultados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
