/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Controlador.MEquipo;
import Modelo.Equipo;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class FormEquipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormEquipos
     */
    public FormEquipos() {
        initComponents();
        this.setSize(910,600);
        this.setTitle("Equipos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Elim = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtNombreEntrenador2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEquipo2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Eliminar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Eliminar = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        ListaEliminar = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        txtNombreEntrenador1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEquipo1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListaModificar = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreEquipo = new javax.swing.JTextField();
        txtNombreEntrenador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Elim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ElimMouseClicked(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreEntrenador2.setEditable(false);
        jPanel2.add(txtNombreEntrenador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, 30));

        jLabel6.setText("Nombre Del Entrenador");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        txtNombreEquipo2.setEditable(false);
        jPanel2.add(txtNombreEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, 30));

        jLabel7.setText("Nombre Del Equipo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        txtID1.setEditable(false);
        jPanel2.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, 30));

        jLabel8.setText("ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        Eliminar1.setText("Eliminar");
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        jPanel2.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        Eliminar.setText("DATOS");
        jScrollPane5.setViewportView(Eliminar);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 490, 440));

        ListaEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEliminarMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(ListaEliminar);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        Elim.addTab("Eliminar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtNombreEntrenador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, 30));

        jLabel5.setText("Nombre Del Entrenador");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        jPanel3.add(txtNombreEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, 30));

        jLabel2.setText("Nombre Del Equipo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        txtID.setEditable(false);
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 90, 30));

        Guardar.setText("GUARDAR");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        jPanel3.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jTextPane2.setText("DATOS");
        jScrollPane6.setViewportView(jTextPane2);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 490, 440));

        ListaModificar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaModificarValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(ListaModificar);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        Elim.addTab("Modificar", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Del Equipo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));
        jPanel1.add(txtNombreEntrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 90, 30));

        jLabel4.setText("Nombre Del Entrenador");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        Elim.addTab("Agregar", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 217, -1, -1));
        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jScrollPane9.setViewportView(Lista);

        jPanel4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 550, 300));

        Elim.addTab("Listar", jPanel4);

        getContentPane().add(Elim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        String NEquipo = txtNombreEquipo.getText();
        String NEntrenador = txtNombreEntrenador.getText();
        if(ValidarCampos(NEquipo,NEntrenador)){
            Equipo equipo = new Equipo(NEquipo,NEntrenador );
            MEquipo dataEquipo = new MEquipo(equipo);
            if(dataEquipo.Agregar()){
                JOptionPane.showMessageDialog(null,"Se Agregó correctamente.");                   
                VaciarCampos();
            }      
        }else{
            JOptionPane.showMessageDialog(null,"Hay datos erroneos");
        }
      
    }//GEN-LAST:event_btnAgregarMouseClicked
    private boolean ValidarCampos(String NEquipo, String NEntrenador){
        if(!NEquipo.equals("") && !NEntrenador.equals("")){
            return true;
        }
        return false;
    }
    DefaultListModel<String> modelo = new DefaultListModel<>();
    private void ElimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ElimMouseClicked

        CrearModelo();
        // TODO add your handling code here:

    }//GEN-LAST:event_ElimMouseClicked

    private void CrearModelo(){
        MEquipo dataEquipo = new MEquipo();
        modelo.clear();
        for(String item : dataEquipo.Listar()){
            modelo.addElement(item);
        }
        Lista.setModel(modelo);
        ListaModificar.setModel(modelo);
        ListaEliminar.setModel(modelo);
    }
    private void ListaModificarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaModificarValueChanged
        // TODO add your handling code here:
        
        if(ListaModificar.getSelectedValue() != null ){
            String[] Datos = ListaModificar.getSelectedValue().split("\\|");
            txtID.setText(Datos[0]);
            txtNombreEquipo1.setText(Datos[1]);
            txtNombreEntrenador1.setText(Datos[2]);
        }
    }//GEN-LAST:event_ListaModificarValueChanged

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        // TODO add your handling code here:
        String NEquipo = txtNombreEquipo1.getText();
        String NEntrenador = txtNombreEntrenador1.getText();
        if(ValidarCampos(NEquipo,NEntrenador)){
            Equipo equipo = new Equipo();
            equipo.setID(Integer.parseInt(txtID.getText()));
            equipo.setNombre_Equipo(NEquipo);
            equipo.setNombre_Entrenador(NEntrenador);
            MEquipo dataEquipo = new MEquipo(equipo);
            if(dataEquipo.Actualizar()){
                JOptionPane.showMessageDialog(null, "Se actualizó correctamente");
            }
            CrearModelo();    
        }else{
            JOptionPane.showMessageDialog(null,"Hay datos erroneos");
        }
    }//GEN-LAST:event_GuardarMouseClicked

    private void ListaEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEliminarMouseClicked
        // TODO add your handling code here:
        if(ListaEliminar.getSelectedValue() != null ){
            String[] Datos = ListaEliminar.getSelectedValue().split("\\|");
            txtID1.setText(Datos[0]);
            txtNombreEquipo2.setText(Datos[1]);
            txtNombreEntrenador2.setText(Datos[2]); 
        }
    }//GEN-LAST:event_ListaEliminarMouseClicked

    private void VaciarCampos(){
        txtNombreEquipo.setText("");
        txtNombreEntrenador.setText("");
        txtID.setText("");
        txtNombreEquipo1.setText("");
        txtNombreEntrenador1.setText("");
        txtID1.setText("");
        txtNombreEquipo2.setText("");
        txtNombreEntrenador2.setText("");
    }
    
    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        // TODO add your handling code here:
        if(ListaEliminar.getSelectedValue() != null){
            int indice = ListaEliminar.getSelectedIndex();
            
            if(indice != -1){
                String elemento = ListaEliminar.getSelectedValue();
                Equipo equipo = new Equipo();
                equipo.setID(Integer.parseInt(txtID1.getText()));
                MEquipo dataEquipo = new MEquipo(equipo);
                if(dataEquipo.Eliminar()){
                    JOptionPane.showMessageDialog(null,"Se eliminó");
                    modelo.removeElement(elemento);
                    VaciarCampos();
                }
            }
        }
    }//GEN-LAST:event_Eliminar1MouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Elim;
    private javax.swing.JTextPane Eliminar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JButton Guardar;
    private javax.swing.JList<String> Lista;
    private javax.swing.JList<String> ListaEliminar;
    private javax.swing.JList<String> ListaModificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtNombreEntrenador;
    private javax.swing.JTextField txtNombreEntrenador1;
    private javax.swing.JTextField txtNombreEntrenador2;
    private javax.swing.JTextField txtNombreEquipo;
    private javax.swing.JTextField txtNombreEquipo1;
    private javax.swing.JTextField txtNombreEquipo2;
    // End of variables declaration//GEN-END:variables
}
