/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.MEquipo;
import Controlador.MPartido;
import Modelo.Equipo;
import Modelo.Partido;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.LocalDate;
import java.util.HashSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class FromPartidos extends javax.swing.JInternalFrame {
    private final String Equipos = "C:\\Users\\pc\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_Partidos\\src\\Archivos\\Equipos.txt";

    /**
     * Creates new form FromPartidos
     */
    public FromPartidos() {
        initComponents();
        this.setSize(910,600);
        this.setTitle("Partidos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eliminar = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        Eliminar1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EquipoLocal2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        EquipoVisitante2 = new javax.swing.JComboBox<>();
        GolesVisitante2 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        GolesLocal2 = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        ListaEliminar = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        GolesLocal1 = new javax.swing.JSpinner();
        EquipoLocal1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EquipoVisitante1 = new javax.swing.JComboBox<>();
        GolesVisitante1 = new javax.swing.JSpinner();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        ListaModificar = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EquipoLocal = new javax.swing.JComboBox<>();
        EquipoVisitante = new javax.swing.JComboBox<>();
        GolesVisitante = new javax.swing.JSpinner();
        GolesLocal = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar1.setText("Eliminar");
        Eliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar1MouseClicked(evt);
            }
        });
        jPanel2.add(Eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel15.setText("ID");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        txtID2.setEditable(false);
        jPanel2.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 30));

        jLabel16.setText("Equipo local");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        EquipoLocal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocal2ActionPerformed(evt);
            }
        });
        jPanel2.add(EquipoLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 100, -1));

        jLabel17.setText("Equipo visitante");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jPanel2.add(EquipoVisitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 110, -1));
        jPanel2.add(GolesVisitante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 110, -1));

        jLabel18.setText("Goles visitante");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
        jPanel2.add(GolesLocal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, -1));

        jLabel19.setText("Goles Local");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jTextPane3.setText("DATOS");
        jScrollPane8.setViewportView(jTextPane3);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 510, 440));

        ListaEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaEliminarMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(ListaEliminar);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        Eliminar.addTab("Eliminar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        txtID.setEditable(false);
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, 30));

        Guardar.setText("GUARDAR");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel3.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel11.setText("Equipo local");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel12.setText("Goles Local");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));
        jPanel3.add(GolesLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, -1));

        EquipoLocal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocal1ActionPerformed(evt);
            }
        });
        jPanel3.add(EquipoLocal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 100, -1));

        jLabel13.setText("Equipo visitante");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jLabel14.setText("Goles visitante");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jPanel3.add(EquipoVisitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 110, -1));
        jPanel3.add(GolesVisitante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 110, -1));

        jTextPane1.setText("DATOS");
        jScrollPane7.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 490, 440));

        ListaModificar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaModificarValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(ListaModificar);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 440));

        jTextField1.setText("jTextField1");
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        Eliminar.addTab("Modificar", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 217, -1, -1));

        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Lista);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 770, 420));

        Eliminar.addTab("Listar", jPanel4);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Goles visitante");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel4.setText("Equipo visitante");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel9.setText("Equipo local");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setText("Goles Local");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        EquipoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocalActionPerformed(evt);
            }
        });
        jPanel1.add(EquipoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, -1));

        jPanel1.add(EquipoVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, -1));
        jPanel1.add(GolesVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 110, -1));
        jPanel1.add(GolesLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        Eliminar.addTab("Agregar", jPanel1);

        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EquipoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoLocalActionPerformed

    private void EquipoLocal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoLocal1ActionPerformed

    private void EquipoLocal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoLocal2ActionPerformed
    private DefaultListModel<String> modelo = new DefaultListModel<>();
    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
        CrearModelo();
        CargarComboBox();
    }//GEN-LAST:event_EliminarMouseClicked

    private void CargarComboBox(){
        CargarModeloLocal(EquipoLocal);
        CargarModeloVisitante(EquipoVisitante);
    }
    private void CargarModeloLocal(JComboBox equipo){
        DefaultComboBoxModel<String> modeloLocal = new DefaultComboBoxModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader(Equipos))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] Datos = linea.split("\\|");
                modeloLocal.addElement(Datos[1]);
            }
            br.close();
            equipo.setModel(modeloLocal);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }
    private void CargarModeloVisitante(JComboBox equipo){
        DefaultComboBoxModel<String> modeloVisitante = new DefaultComboBoxModel<>();
        try (BufferedReader br = new BufferedReader(new FileReader(Equipos))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] Datos = linea.split("\\|");
                modeloVisitante.addElement(Datos[1]);
            }
            br.close();
            equipo.setModel(modeloVisitante);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void CrearModelo(){
        MPartido dataPartido = new MPartido();
        modelo.clear();
        for(String item : dataPartido.Listar()){
            modelo.addElement(item);
        }
        Lista.setModel(modelo);
        ListaModificar.setModel(modelo);
        ListaEliminar.setModel(modelo);
    }
    private void ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        String ELocal = (String) EquipoLocal.getSelectedItem();
        String EVisitante = (String) EquipoVisitante.getSelectedItem();
        int GLocal = (int) GolesLocal.getValue();
        int GVisitante = (int) GolesVisitante.getValue();

        if(ValidarCampos(GLocal,GVisitante,ELocal,EVisitante)){

            Partido partido = new Partido(ELocal,GLocal,EVisitante,GVisitante);
            MPartido dataPartido = new MPartido(partido);

            if(dataPartido.Agregar()){
                JOptionPane.showMessageDialog(null,"Se agregó");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Hay valores incorrectos.");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private boolean ValidarCampos(int GLocal,int GVisitante, String ELocal, String EVisitante){
        if(GLocal >= 0 || GVisitante >= 0){
            if(!ELocal.equals("") && !ELocal.equals("")){
                if(!ELocal.equals(EVisitante)){
                    return true;
                }
            }
        }
        return false;
    }
    private void ListaModificarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaModificarValueChanged
        // TODO add your handling code here:
        if(ListaModificar.getSelectedValue() != null ){
            CargarModeloVisitante(EquipoLocal1);
            CargarModeloLocal(EquipoVisitante1);
            String[] Datos = ListaModificar.getSelectedValue().split("\\|");
            EquipoLocal1.setSelectedItem(Datos[1]);
            EquipoVisitante1.setSelectedItem(Datos[3]);
            txtID.setText(Datos[0]);
            GolesLocal1.setValue(Integer.parseInt(Datos[2]));
            GolesVisitante1.setValue(Integer.parseInt(Datos[4]));
        }
    }//GEN-LAST:event_ListaModificarValueChanged

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        // TODO add your handling code here:
        try{
            String ELocal = (String) EquipoLocal1.getSelectedItem();
            String EVisitante = (String) EquipoVisitante1.getSelectedItem();
            int GLocal = (int) GolesLocal1.getValue();
            int GVisitante = (int) GolesVisitante1.getValue();
            int ID = Integer.parseInt(txtID.getText());
            if(ValidarCampos(GLocal,GVisitante,ELocal,EVisitante)){
                Partido partido = new Partido();
                partido.setID(ID);
                partido.setEquipo_Local(ELocal);
                partido.setGoles_Local(GLocal);

                partido.setEquipo_Visitante(EVisitante);
                partido.setGoles_Visitante(GVisitante);
                partido.setFecha(LocalDate.now());


                MPartido dataPartido = new MPartido(partido);
                if(dataPartido.Actualizar()){
                    JOptionPane.showMessageDialog(null, "Se actualizó correctamente");
                }
                CrearModelo();        
            }else{
                JOptionPane.showMessageDialog(null,"Hay datos incorrectos.");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Hay valores incorrectos.");
        }
    }//GEN-LAST:event_GuardarMouseClicked

    private void ListaEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaEliminarMouseClicked
        // TODO add your handling code here:
        if(ListaEliminar.getSelectedValue() != null ){
            CargarModeloVisitante(EquipoLocal2);
            CargarModeloLocal(EquipoVisitante2);
            String[] Datos = ListaEliminar.getSelectedValue().split("\\|");
            EquipoLocal2.setSelectedItem(Datos[1]);
            EquipoVisitante2.setSelectedItem(Datos[3]);
            txtID2.setText(Datos[0]);
            GolesLocal2.setValue(Integer.parseInt(Datos[2]));
            GolesVisitante2.setValue(Integer.parseInt(Datos[4]));
        }
    }//GEN-LAST:event_ListaEliminarMouseClicked

    private void Eliminar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar1MouseClicked
        // TODO add your handling code here:
       try{
            if(ListaEliminar.getSelectedValue() != null){
                int indice = ListaEliminar.getSelectedIndex();

                if(indice != -1){
                    String elemento = ListaEliminar.getSelectedValue();
                    Partido partido = new Partido();
                    partido.setID(Integer.parseInt(txtID2.getText()));

                    MPartido dataPartido = new MPartido(partido);
                    if(dataPartido.Eliminar()){
                        JOptionPane.showMessageDialog(null,"Se eliminó");
                        modelo.removeElement(elemento);
                        VaciarCampos();
                    }
                }
            }       
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,"Hay datos incorrectos");
       }

    }//GEN-LAST:event_Eliminar1MouseClicked

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void VaciarCampos(){
        txtID2.setText("");
        GolesLocal2.setValue(0);
        GolesVisitante2.setValue(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Eliminar;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JComboBox<String> EquipoLocal;
    private javax.swing.JComboBox<String> EquipoLocal1;
    private javax.swing.JComboBox<String> EquipoLocal2;
    private javax.swing.JComboBox<String> EquipoVisitante;
    private javax.swing.JComboBox<String> EquipoVisitante1;
    private javax.swing.JComboBox<String> EquipoVisitante2;
    private javax.swing.JSpinner GolesLocal;
    private javax.swing.JSpinner GolesLocal1;
    private javax.swing.JSpinner GolesLocal2;
    private javax.swing.JSpinner GolesVisitante;
    private javax.swing.JSpinner GolesVisitante1;
    private javax.swing.JSpinner GolesVisitante2;
    private javax.swing.JButton Guardar;
    private javax.swing.JList<String> Lista;
    private javax.swing.JList<String> ListaEliminar;
    private javax.swing.JList<String> ListaModificar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID2;
    // End of variables declaration//GEN-END:variables
}
