/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.BufferedWriter;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class Principal extends javax.swing.JFrame {

    private FromPartidos formPartido;
    private FormEquipos formEquipos;
    private FormResultados formResultados;
    private FileWriter fileWriter;
    private  BufferedWriter bufferedWriter;
    private String Partidos = "C:\\Users\\pc\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_Partidos\\src\\Archivos\\Partidos.txt";
    private String Equipos = "C:\\Users\\pc\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_Partidos\\src\\Archivos\\Equipos.txt";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnEquipos = new javax.swing.JMenu();
        btnPartidos = new javax.swing.JMenu();
        btnResultados = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 650));

        btnEquipos.setText("Equipos");
        btnEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEquiposMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEquipos);

        btnPartidos.setText("Partidos");
        btnPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPartidosMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnPartidos);

        btnResultados.setText("Resultados");
        btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultadosMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnResultados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        File ArchivoPartidos = new File(Partidos);
        File ArchivoEquipos = new File(Equipos);

        if(!ArchivoPartidos.exists() && ArchivoPartidos.isFile()){
            CrearArchivo(Partidos);
            if(!ArchivoEquipos.exists() && ArchivoEquipos.exists()){
                CrearArchivo(Equipos);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void CrearArchivo(String ruta){
        try{
            File archivo = new File(ruta);
            archivo.createNewFile();
            
        }catch(Exception ex){
            JOptionPane.showInputDialog(ex.getMessage());
        }
    }
    private void btnEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEquiposMouseClicked
        // TODO add your handling code here:
        if(formEquipos == null || formEquipos.isClosed()){
            formEquipos = new FormEquipos();
            Contenedor.add(formEquipos);
        }
        formEquipos.setVisible(true);
    }//GEN-LAST:event_btnEquiposMouseClicked

    private void btnPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPartidosMouseClicked
        if(formPartido == null || formPartido.isClosed()){
            formPartido = new FromPartidos();
            Contenedor.add(formPartido);
        }
        formPartido.setVisible(true);
    }//GEN-LAST:event_btnPartidosMouseClicked

    private void btnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMouseClicked
        // TODO add your handling code here:
        if(formResultados == null || formResultados.isClosed()){
            formResultados = new FormResultados();
            Contenedor.add(formResultados);
        }
        formResultados.setVisible(true);
    }//GEN-LAST:event_btnResultadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Contenedor;
    private javax.swing.JMenu btnEquipos;
    private javax.swing.JMenu btnPartidos;
    private javax.swing.JMenu btnResultados;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
